### ISSUE TITLE
 Division by zero CI

### ISSUE THREAD

**Issue by ozkula** [jerrywham/phpGraph#1]
hi, i got php error using CI

Message: Division by zero
Filename: libraries/Phpgraph.php
Line Number: 1296

when only 1 data available, how can i resolve this?

**Comment by jerrywham** [comment]
Change 

``` php
$stepX = $width / ($lenght - 1);
```

by

``` php
$stepX = $width / ($lenght <= 1 ? $lenght : ($lenght - 1));
```
